### ISSUE TITLE
Thread safety warning

### ISSUE THREAD

**Issue by ryanburnette** [britg/sinatra-cross_origin#20]
I get a thread safety warning when I add this Gem to my Sinatra app.

```
WARN: tilt autoloading 'tilt/erb' in a non thread-safe way; explicit require 'tilt/erb' suggested.
```

**Comment by ryanburnette** [comment]
I tried to dig into this and I have absolutely no idea why the usage of this Gem spawns that error. I'm just going to close this and re-open it if I ever figure anything out.

**Comment by xprazak2** [comment]
hi @ryanburnette, not sure if this is still an issue, but I encountered exactly the same warning today with Sinatra 1.4.6 and tilt 2.0.1. I added `require 'tilt/erb'` to my project and it made the warning go away.
